Repository OpenDevicePartnership/embedded-services, pull requests merged in 2025-07, with the labels that each got.

#362 Fix clippy workflow
  .github/workflows/check.yml
Labels: bug

#372 Update dependencies and replace Cell and RefCell with SyncCell and Mutex, respectively
  Cargo.lock
  battery-service/src/context.rs
  battery-service/src/device.rs
  battery-service/src/wrapper.rs
  cfu-service/src/buffer.rs
  embedded-service/src/activity.rs
  embedded-service/src/buffer.rs
  embedded-service/src/cfu/component.rs
  embedded-service/src/cfu/mod.rs
  embedded-service/src/comms.rs
  embedded-service/src/critical_section_cell.rs
  embedded-service/src/hid/mod.rs
  embedded-service/src/intrusive_list.rs
  embedded-service/src/ipc/deferred.rs
  embedded-service/src/keyboard.rs
  embedded-service/src/lib.rs
  embedded-service/src/power/policy/charger.rs
  embedded-service/src/power/policy/device.rs
  embedded-service/src/power/policy/policy.rs
  embedded-service/src/type_c/controller.rs
  espi-service/src/espi_service.rs
  hid-service/src/i2c/device.rs
  hid-service/src/i2c/host.rs
  hid-service/src/i2c/passthrough/interrupt.rs
  platform-service/src/imxrt/embedded_crc.rs
  platform-service/src/nvram.rs
  platform-service/src/reset.rs
  power-policy-service/src/charger.rs
  power-policy-service/src/lib.rs
  type-c-service/src/driver/tps6699x.rs
  type-c-service/src/task.rs
  type-c-service/src/wrapper/mod.rs
  type-c-service/src/wrapper/power.rs
Labels: bug, cargo vet

#385 Quiet down battery state machine prints when collecting dynamic and static data
  battery-service/src/context.rs
Labels: enhancement

#399 power-policy: Add unconstrained logic
  embedded-service/src/power/policy/action/device.rs
  embedded-service/src/power/policy/action/policy.rs
  embedded-service/src/power/policy/device.rs
  embedded-service/src/power/policy/flags.rs
  embedded-service/src/power/policy/mod.rs
  embedded-service/src/power/policy/policy.rs
  examples/std/src/bin/power_policy.rs
  power-policy-service/src/consumer.rs
  power-policy-service/src/lib.rs
  power-policy-service/src/provider.rs
  type-c-service/src/wrapper/power.rs
Labels: BREAKING CHANGE

#415 Make `type_c_service::task` module public
  type-c-service/src/lib.rs
Labels: type-c

#420 Update rt633 example dependencies and fix breakage
  examples/rt633/Cargo.lock
  examples/rt633/src/bin/espi.rs
Labels: dependencies

#411 power-policy: Broadcast events
  embedded-service/src/power/policy/mod.rs
  embedded-service/src/power/policy/policy.rs
  examples/std/src/bin/power_policy.rs
  power-policy-service/src/lib.rs
Labels: cargo vet

#390 Type-c: Event loop refactoring
  Cargo.lock
  embedded-service/src/type_c/controller.rs
  embedded-service/src/type_c/event.rs
  examples/rt685s-evk/src/bin/type_c.rs
  examples/rt685s-evk/src/bin/type_c_cfu.rs
  examples/std/src/bin/type_c/service.rs
  type-c-service/Cargo.toml
  type-c-service/src/driver/tps6699x.rs
  type-c-service/src/lib.rs
  type-c-service/src/task.rs
  type-c-service/src/wrapper/cfu.rs
  type-c-service/src/wrapper/mod.rs
  type-c-service/src/wrapper/pd.rs
  type-c-service/src/wrapper/power.rs
Labels: BREAKING CHANGE

#410 Remove unused stuff
  Cargo.lock
  Cargo.toml
  storage-bus/Cargo.toml
  storage-bus/README.md
  storage-bus/src/lib.rs
  storage-bus/src/nand.rs
  storage-bus/src/nor.rs
Labels: cargo vet, BREAKING CHANGE

#439 Add wait for `APP1` mode when updating port status
  type-c-service/src/driver/tps6699x.rs
Labels: type-c
