Repository OpenDevicePartnership/embedded-services, pull requests merged in 2025-09, with the labels that each got.

#449 add debug service
  Cargo.lock
  Cargo.toml
  debug-service/Cargo.toml
  debug-service/src/debug_service.rs
  debug-service/src/defmt_ring_logger.rs
  debug-service/src/lib.rs
  embedded-service/src/ec_type/protocols/mctp.rs
  embedded-service/src/fmt.rs
  examples/std/Cargo.lock
  examples/std/Cargo.toml
  examples/std/src/bin/debug.rs
  supply-chain/audits.toml
  supply-chain/config.toml
  supply-chain/imports.lock
Labels: cargo vet

#492 type-c-service/tps6699x: Remove redundant mutexes and flatten async
  Cargo.lock
  embedded-service/src/type_c/controller.rs
  examples/rt685s-evk/Cargo.lock
  examples/std/Cargo.lock
  examples/std/src/lib/type_c/mock_controller.rs
  type-c-service/Cargo.toml
  type-c-service/src/driver/tps6699x.rs
Labels: cargo vet, BREAKING CHANGE

#497 type-c-service/wrapper: Remove port count generics
  examples/rt685s-evk/src/bin/type_c.rs
  examples/rt685s-evk/src/bin/type_c_cfu.rs
  examples/std/src/bin/type_c/external.rs
  examples/std/src/bin/type_c/service.rs
  examples/std/src/bin/type_c/unconstrained.rs
  examples/std/src/lib/type_c/mock_controller.rs
  type-c-service/src/driver/tps6699x.rs
  type-c-service/src/wrapper/backing.rs
  type-c-service/src/wrapper/cfu.rs
  type-c-service/src/wrapper/dp.rs
  type-c-service/src/wrapper/mod.rs
  type-c-service/src/wrapper/pd.rs
  type-c-service/src/wrapper/power.rs
  type-c-service/src/wrapper/vdm.rs
Labels: BREAKING CHANGE

#498 type-c-service: Thread UCSI port commands to hardware
  Cargo.lock
  embedded-service/src/type_c/controller.rs
  examples/rt633/Cargo.lock
  examples/rt685s-evk/Cargo.lock
  examples/std/Cargo.lock
  examples/std/src/bin/type_c/basic.rs
  examples/std/src/bin/type_c/ucsi.rs
  examples/std/src/lib/type_c/mock_controller.rs
  type-c-service/src/driver/tps6699x.rs
  type-c-service/src/service/config.rs
  type-c-service/src/service/ucsi.rs
  type-c-service/src/wrapper/pd.rs
Labels: BREAKING CHANGE

#502 move get hid descriptor before borrowing
  hid-service/src/i2c/device.rs
Labels: bug
