Repository OpenDevicePartnership/embedded-services, pull requests merged in 2025-08, with the labels that each got.

#433 Add cfu update abort
  cfu-service/src/buffer.rs
  cfu-service/src/lib.rs
  cfu-service/src/splitter.rs
  embedded-service/src/cfu/component.rs
  examples/std/src/bin/cfu_buffer.rs
  examples/std/src/bin/cfu_splitter.rs
  type-c-service/src/wrapper/cfu.rs
Labels: BREAKING CHANGE

#444 Handle MCTP OOB messages in espi service and forward payload to subsystems
  embedded-service/src/buffer.rs
  embedded-service/src/ec_type/message.rs
  embedded-service/src/ec_type/mod.rs
  embedded-service/src/ec_type/protocols/mctp.rs
  embedded-service/src/ec_type/protocols/mod.rs
  espi-service/src/espi_service.rs
Labels: enhancement

#450 Add external functions for new 4CC commands
  embedded-service/src/type_c/controller.rs
  embedded-service/src/type_c/external.rs
  examples/std/src/lib/type_c/mock_controller.rs
  type-c-service/src/driver/tps6699x.rs
  type-c-service/src/task.rs
  type-c-service/src/wrapper/pd.rs
Labels: type-c

#445 type-c-service: UCSI PPM implementation
  Cargo.lock
  embedded-service/src/type_c/controller.rs
  embedded-service/src/type_c/external.rs
  examples/rt685s-evk/Cargo.lock
  examples/rt685s-evk/src/bin/type_c.rs
  examples/rt685s-evk/src/bin/type_c_cfu.rs
  examples/std/Cargo.lock
  examples/std/Cargo.toml
  examples/std/src/bin/type_c/external.rs
  examples/std/src/bin/type_c/service.rs
  examples/std/src/bin/type_c/ucsi.rs
  examples/std/src/bin/type_c/unconstrained.rs
  supply-chain/audits.toml
  type-c-service/src/lib.rs
  type-c-service/src/service/config.rs
  type-c-service/src/service/controller.rs
  type-c-service/src/service/mod.rs
  type-c-service/src/service/port.rs
  type-c-service/src/service/power.rs
  type-c-service/src/service/ucsi.rs
  type-c-service/src/task.rs
Labels: cargo vet, BREAKING CHANGE, type-c

#452 Fix bug where external and internal vbus switch were swapped
  type-c-service/src/driver/tps6699x.rs
Labels: type-c

#454 battery-service: Receive PSU state from power policy
  battery-service/src/acpi.rs
  battery-service/src/context.rs
  battery-service/src/lib.rs
  power-policy-service/src/consumer.rs
Labels: enhancement

#422 CODEOWNERS: add subsystem owner teams
  CODEOWNERS
Labels: enhancement

#383 Implement initial thermal service
  Cargo.lock
  Cargo.toml
  examples/std/Cargo.lock
  examples/std/Cargo.toml
  examples/std/src/bin/thermal.rs
  supply-chain/audits.toml
  thermal-service/Cargo.toml
  thermal-service/src/context.rs
  thermal-service/src/fan.rs
  thermal-service/src/lib.rs
  thermal-service/src/mctp.rs
  thermal-service/src/mptf.rs
  thermal-service/src/sensor.rs
  thermal-service/src/utils.rs
Labels: cargo vet

#457 type-c-service/wrapper: Migrate event loop over to wait/process/finalize
  embedded-service/src/cfu/component.rs
  embedded-service/src/ipc/deferred.rs
  embedded-service/src/power/policy/device.rs
  embedded-service/src/type_c/controller.rs
  embedded-service/src/type_c/event.rs
  embedded-service/src/type_c/external.rs
  embedded-service/src/type_c/mod.rs
  examples/rt685s-evk/src/bin/type_c.rs
  examples/rt685s-evk/src/bin/type_c_cfu.rs
  examples/std/Cargo.lock
  examples/std/src/bin/type_c/basic.rs
  examples/std/src/bin/type_c/external.rs
  examples/std/src/bin/type_c/service.rs
  examples/std/src/lib/type_c/mock_controller.rs
  type-c-service/src/driver/tps6699x.rs
  type-c-service/src/service/mod.rs
  type-c-service/src/service/port.rs
  type-c-service/src/wrapper/cfu.rs
  type-c-service/src/wrapper/message.rs
  type-c-service/src/wrapper/mod.rs
  type-c-service/src/wrapper/pd.rs
  type-c-service/src/wrapper/power.rs
Labels: BREAKING CHANGE

#472 Uprev embassy-imxrt to latest version for espi-service
  Cargo.lock
  espi-service/src/espi_service.rs
  examples/rt633/Cargo.lock
  examples/rt685s-evk/Cargo.lock
Labels: enhancement, espi

#474 espi-service: Support multiple OOB response packets
  battery-service/src/acpi.rs
  battery-service/src/context.rs
  embedded-service/src/ec_type/protocols/mctp.rs
  espi-service/src/espi_service.rs
Labels: enhancement

#470 Pull in breaking embedded-usb-pd port ID changes
  Cargo.lock
  embedded-service/src/type_c/controller.rs
  embedded-service/src/type_c/external.rs
  examples/rt633/Cargo.lock
  examples/rt685s-evk/Cargo.lock
  examples/std/Cargo.lock
  examples/std/src/bin/type_c/basic.rs
  examples/std/src/lib/type_c/mock_controller.rs
  type-c-service/src/driver/tps6699x.rs
  type-c-service/src/service/ucsi.rs
  type-c-service/src/wrapper/message.rs
  type-c-service/src/wrapper/mod.rs
  type-c-service/src/wrapper/vdm.rs
Labels: cargo vet
