Repository OpenDevicePartnership/embedded-services, pull requests merged in 2025-06, with the labels that each got.

#349 Power Policy Charger Updates
  embedded-service/src/power/policy/charger.rs
  embedded-service/src/power/policy/mod.rs
  embedded-service/src/power/policy/policy.rs
  power-policy-service/src/charger.rs
  power-policy-service/src/consumer.rs
Labels: enhancement, BREAKING CHANGE

#355 Force charger CheckReady and Init sequence even if no previous consumer exists
  power-policy-service/src/consumer.rs
Labels: enhancement

#359 Add charger unpowered check to idle Policy
  power-policy-service/src/consumer.rs
Labels: bug

#297 Add IPC deferred channel tests.
  Cargo.lock
  Cargo.toml
  embedded-service/Cargo.toml
  embedded-service/src/ipc/deferred.rs
  supply-chain/audits.toml
  supply-chain/imports.lock
Labels: cargo vet

#342 type-c-service: Move controller sync state functionality to external API
  embedded-service/src/type_c/controller.rs
  embedded-service/src/type_c/external.rs
  examples/rt685s-evk/src/bin/type_c.rs
  examples/std/src/bin/type_c/basic.rs
  type-c-service/src/task.rs
  type-c-service/src/wrapper/mod.rs
  type-c-service/src/wrapper/pd.rs
Labels: cargo vet

#367 Battery service: add context config, async state getter, and remove autonomous state machine logic
  battery-service/src/context.rs
  battery-service/src/controller.rs
  battery-service/src/lib.rs
  battery-service/src/wrapper.rs
Labels: enhancement

#375 Only send `SRDY` after Sink Ready interrupt
  type-c-service/src/wrapper/mod.rs
  type-c-service/src/wrapper/power.rs
Labels: bug, type-c
