Repository OpenDevicePartnership/embedded-services, pull requests merged in 2025-02, with the labels that each got.

#95 Fix license text
  LICENSE
Labels: documentation

#104 Update embassy-executor and embassy-time to latest version
  examples/rt685s-evk/Cargo.toml
  examples/std/Cargo.toml
Labels: bug

#100 Create initial power policy implementation
  .vscode/settings.json
  docs/power-policy.md
  embedded-service/src/lib.rs
  embedded-service/src/power/mod.rs
  embedded-service/src/power/policy/action/device.rs
  embedded-service/src/power/policy/action/mod.rs
  embedded-service/src/power/policy/action/policy.rs
  embedded-service/src/power/policy/device.rs
  embedded-service/src/power/policy/mod.rs
  embedded-service/src/power/policy/policy.rs
  examples/std/Cargo.toml
  examples/std/src/bin/power_policy.rs
  power-policy-service/Cargo.toml
  power-policy-service/src/lib.rs
Labels: enhancement

#105 embedded-service: refactor logging macros
  .github/workflows/check.yml
  embedded-service/src/fmt.rs
  power-button-service/Cargo.toml
Labels: enhancement

#113 Add standard EC types
  embedded-service/src/ec_type/message.rs
  embedded-service/src/ec_type/mod.rs
  embedded-service/src/ec_type/structure.rs
  embedded-service/src/lib.rs
Labels: enhancement

#108 Std examples embassy-sync version fix
  examples/std/Cargo.toml
Labels: bug
